/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  AddCustomCodeInput,
  AddSectionInput,
  AssociateCodesetInput,
  AssociateCodesetResponse,
  BodyRunInlineConfigurationTest,
  ConfigurationCustomCodeResponse,
  ConfigurationStatusUpdateResponse,
  ConfigurationTestResponse,
  ConfirmUploadCustomCodesInput,
  CreateConfigInput,
  CreateConfigurationResponse,
  DeleteSectionInput,
  GetConfigurationResponse,
  GetConfigurationsResponse,
  HTTPValidationError,
  SectionUpdateInput,
  UpdateCustomCodeInput,
  UploadCustomCodesCsvInput,
  UploadCustomCodesPreviewResponse,
  UploadCustomCodesResponse,
  ValidateCustomCodeInput,
  ValidateCustomCodeResponse
} from '../schemas';





/**
 * Returns a list of configurations based on the logged-in user.

Returns:
    List of configuration objects.
 * @summary Get Configurations
 */
export const getConfigurations = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetConfigurationsResponse[]>> => {
    
    
    return axios.default.get(
      `/api/v1/configurations/`,options
    );
  }




export const getGetConfigurationsQueryKey = () => {
    return [
    `/api/v1/configurations/`
    ] as const;
    }

    
export const getGetConfigurationsQueryOptions = <TData = Awaited<ReturnType<typeof getConfigurations>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfigurations>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetConfigurationsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getConfigurations>>> = ({ signal }) => getConfigurations({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getConfigurations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetConfigurationsQueryResult = NonNullable<Awaited<ReturnType<typeof getConfigurations>>>
export type GetConfigurationsQueryError = AxiosError<unknown>


export function useGetConfigurations<TData = Awaited<ReturnType<typeof getConfigurations>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfigurations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConfigurations>>,
          TError,
          Awaited<ReturnType<typeof getConfigurations>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConfigurations<TData = Awaited<ReturnType<typeof getConfigurations>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfigurations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConfigurations>>,
          TError,
          Awaited<ReturnType<typeof getConfigurations>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConfigurations<TData = Awaited<ReturnType<typeof getConfigurations>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfigurations>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Configurations
 */

export function useGetConfigurations<TData = Awaited<ReturnType<typeof getConfigurations>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfigurations>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetConfigurationsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Create a new configuration for a jurisdiction.
 * @summary Create Configuration
 */
export const createConfiguration = (
    createConfigInput: CreateConfigInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CreateConfigurationResponse>> => {
    
    
    return axios.default.post(
      `/api/v1/configurations/`,
      createConfigInput,options
    );
  }



export const getCreateConfigurationMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createConfiguration>>, TError,{data: CreateConfigInput}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof createConfiguration>>, TError,{data: CreateConfigInput}, TContext> => {

const mutationKey = ['createConfiguration'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createConfiguration>>, {data: CreateConfigInput}> = (props) => {
          const {data} = props ?? {};

          return  createConfiguration(data,axiosOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateConfigurationMutationResult = NonNullable<Awaited<ReturnType<typeof createConfiguration>>>
    export type CreateConfigurationMutationBody = CreateConfigInput
    export type CreateConfigurationMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Create Configuration
 */
export const useCreateConfiguration = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createConfiguration>>, TError,{data: CreateConfigInput}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createConfiguration>>,
        TError,
        {data: CreateConfigInput},
        TContext
      > => {
      return useMutation(getCreateConfigurationMutationOptions(options), queryClient);
    }
    /**
 * Get a single configuration by its ID including all associated conditions.
 * @summary Get Configuration
 */
export const getConfiguration = (
    configurationId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<GetConfigurationResponse>> => {
    
    
    return axios.default.get(
      `/api/v1/configurations/${configurationId}`,options
    );
  }




export const getGetConfigurationQueryKey = (configurationId: string,) => {
    return [
    `/api/v1/configurations/${configurationId}`
    ] as const;
    }

    
export const getGetConfigurationQueryOptions = <TData = Awaited<ReturnType<typeof getConfiguration>>, TError = AxiosError<HTTPValidationError>>(configurationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfiguration>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetConfigurationQueryKey(configurationId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getConfiguration>>> = ({ signal }) => getConfiguration(configurationId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(configurationId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getConfiguration>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetConfigurationQueryResult = NonNullable<Awaited<ReturnType<typeof getConfiguration>>>
export type GetConfigurationQueryError = AxiosError<HTTPValidationError>


export function useGetConfiguration<TData = Awaited<ReturnType<typeof getConfiguration>>, TError = AxiosError<HTTPValidationError>>(
 configurationId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfiguration>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConfiguration>>,
          TError,
          Awaited<ReturnType<typeof getConfiguration>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConfiguration<TData = Awaited<ReturnType<typeof getConfiguration>>, TError = AxiosError<HTTPValidationError>>(
 configurationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfiguration>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConfiguration>>,
          TError,
          Awaited<ReturnType<typeof getConfiguration>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConfiguration<TData = Awaited<ReturnType<typeof getConfiguration>>, TError = AxiosError<HTTPValidationError>>(
 configurationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfiguration>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Configuration
 */

export function useGetConfiguration<TData = Awaited<ReturnType<typeof getConfiguration>>, TError = AxiosError<HTTPValidationError>>(
 configurationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfiguration>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetConfigurationQueryOptions(configurationId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Associate a specified code set with the given configuration.

Args:
    configuration_id (UUID): ID of the configuration
    body (AssociateCodesetInput): payload containing a condition_id
    user (dict[str, Any], optional): User making the request
    db (AsyncDatabaseConnection, optional): Database connection

Raises:
    HTTPException: 404 if configuration is not found in JD
    HTTPException: 404 if configuration is not found
    HTTPException: 409 if configuration is not a draft and therefore not editable
    HTTPException: 500 if configuration cannot be updated

Returns:
    AssociateCodesetResponse: ID of updated configuration, the full list of included conditions,
          and the condition_name
 * @summary Associate Condition Codeset With Configuration
 */
export const associateConditionWithConfiguration = (
    configurationId: string,
    associateCodesetInput: AssociateCodesetInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AssociateCodesetResponse>> => {
    
    
    return axios.default.put(
      `/api/v1/configurations/${configurationId}/code-sets`,
      associateCodesetInput,options
    );
  }



export const getAssociateConditionWithConfigurationMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof associateConditionWithConfiguration>>, TError,{configurationId: string;data: AssociateCodesetInput}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof associateConditionWithConfiguration>>, TError,{configurationId: string;data: AssociateCodesetInput}, TContext> => {

const mutationKey = ['associateConditionWithConfiguration'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof associateConditionWithConfiguration>>, {configurationId: string;data: AssociateCodesetInput}> = (props) => {
          const {configurationId,data} = props ?? {};

          return  associateConditionWithConfiguration(configurationId,data,axiosOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AssociateConditionWithConfigurationMutationResult = NonNullable<Awaited<ReturnType<typeof associateConditionWithConfiguration>>>
    export type AssociateConditionWithConfigurationMutationBody = AssociateCodesetInput
    export type AssociateConditionWithConfigurationMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Associate Condition Codeset With Configuration
 */
export const useAssociateConditionWithConfiguration = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof associateConditionWithConfiguration>>, TError,{configurationId: string;data: AssociateCodesetInput}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof associateConditionWithConfiguration>>,
        TError,
        {configurationId: string;data: AssociateCodesetInput},
        TContext
      > => {
      return useMutation(getAssociateConditionWithConfigurationMutationOptions(options), queryClient);
    }
    /**
 * Remove a specified code set from the given configuration.

Args:
    configuration_id (UUID): ID of the configuration
    condition_id (UUID): ID of the condition to remove
    user (DbUser): User making the request
    db (AsyncDatabaseConnection): Database connection

Raises:
    HTTPException: 404 if configuration is not found in JD
    HTTPException: 404 if condition is not found
    HTTPException: 409 if trying to remove the main condition
    HTTPException: 409 if configuration is not a draft and therefore not editable
    HTTPException: 500 if configuration is cannot be updated

Returns:
    AssociateCodesetResponse: ID of updated configuration and the full list
    of included conditions plus condition_name
 * @summary Remove Condition Codeset From Configuration
 */
export const disassociateConditionWithConfiguration = (
    configurationId: string,
    conditionId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AssociateCodesetResponse>> => {
    
    
    return axios.default.delete(
      `/api/v1/configurations/${configurationId}/code-sets/${conditionId}`,options
    );
  }



export const getDisassociateConditionWithConfigurationMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof disassociateConditionWithConfiguration>>, TError,{configurationId: string;conditionId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof disassociateConditionWithConfiguration>>, TError,{configurationId: string;conditionId: string}, TContext> => {

const mutationKey = ['disassociateConditionWithConfiguration'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof disassociateConditionWithConfiguration>>, {configurationId: string;conditionId: string}> = (props) => {
          const {configurationId,conditionId} = props ?? {};

          return  disassociateConditionWithConfiguration(configurationId,conditionId,axiosOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DisassociateConditionWithConfigurationMutationResult = NonNullable<Awaited<ReturnType<typeof disassociateConditionWithConfiguration>>>
    
    export type DisassociateConditionWithConfigurationMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Remove Condition Codeset From Configuration
 */
export const useDisassociateConditionWithConfiguration = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof disassociateConditionWithConfiguration>>, TError,{configurationId: string;conditionId: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof disassociateConditionWithConfiguration>>,
        TError,
        {configurationId: string;conditionId: string},
        TContext
      > => {
      return useMutation(getDisassociateConditionWithConfigurationMutationOptions(options), queryClient);
    }
    /**
 * Add a user-defined custom code to a configuration.

Args:
    configuration_id (UUID): The ID of the configuration to update.
    body (AddCustomCodeInput): The custom code information provided by the user.
    user (dict[str, Any]): The logged-in user.
    db (AsyncDatabaseConnection): The database connection.

Raises:
    HTTPException: 404 if configuration isn't found
    HTTPException: 409 if configuration is not a draft and therefore not editable
    HTTPException: 500 if custom code can't be added

Returns:
    ConfigurationCustomCodeResponse: Updated configuration
 * @summary Add Custom Code
 */
export const addCustomCodeToConfiguration = (
    configurationId: string,
    addCustomCodeInput: AddCustomCodeInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ConfigurationCustomCodeResponse>> => {
    
    
    return axios.default.post(
      `/api/v1/configurations/${configurationId}/custom-codes`,
      addCustomCodeInput,options
    );
  }



export const getAddCustomCodeToConfigurationMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addCustomCodeToConfiguration>>, TError,{configurationId: string;data: AddCustomCodeInput}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof addCustomCodeToConfiguration>>, TError,{configurationId: string;data: AddCustomCodeInput}, TContext> => {

const mutationKey = ['addCustomCodeToConfiguration'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addCustomCodeToConfiguration>>, {configurationId: string;data: AddCustomCodeInput}> = (props) => {
          const {configurationId,data} = props ?? {};

          return  addCustomCodeToConfiguration(configurationId,data,axiosOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AddCustomCodeToConfigurationMutationResult = NonNullable<Awaited<ReturnType<typeof addCustomCodeToConfiguration>>>
    export type AddCustomCodeToConfigurationMutationBody = AddCustomCodeInput
    export type AddCustomCodeToConfigurationMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Add Custom Code
 */
export const useAddCustomCodeToConfiguration = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addCustomCodeToConfiguration>>, TError,{configurationId: string;data: AddCustomCodeInput}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addCustomCodeToConfiguration>>,
        TError,
        {configurationId: string;data: AddCustomCodeInput},
        TContext
      > => {
      return useMutation(getAddCustomCodeToConfigurationMutationOptions(options), queryClient);
    }
    /**
 * Modify a configuration's custom code based on system/code pair.

Args:
    configuration_id (UUID): The ID of the configuration to modify.
    body (UpdateCustomCodeInput): User-provided object containing custom code info.
    user (dict[str, Any]): The logged-in user.
    db (AsyncDatabaseConnection): The database connection.

Raises:
    HTTPException: 400 if a system is not provided
    HTTPException: 400 if a code is not provided
    HTTPException: 404 if the configuration can't be found
    HTTPException: 409 if configuration is not a draft and therefore not editable
    HTTPException: 500 if the configuration can't be updated

Returns:
    ConfigurationCustomCodeResponse: The updated configuration.
 * @summary Edit Custom Code
 */
export const editCustomCodeFromConfiguration = (
    configurationId: string,
    updateCustomCodeInput: UpdateCustomCodeInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ConfigurationCustomCodeResponse>> => {
    
    
    return axios.default.put(
      `/api/v1/configurations/${configurationId}/custom-codes`,
      updateCustomCodeInput,options
    );
  }



export const getEditCustomCodeFromConfigurationMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editCustomCodeFromConfiguration>>, TError,{configurationId: string;data: UpdateCustomCodeInput}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof editCustomCodeFromConfiguration>>, TError,{configurationId: string;data: UpdateCustomCodeInput}, TContext> => {

const mutationKey = ['editCustomCodeFromConfiguration'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof editCustomCodeFromConfiguration>>, {configurationId: string;data: UpdateCustomCodeInput}> = (props) => {
          const {configurationId,data} = props ?? {};

          return  editCustomCodeFromConfiguration(configurationId,data,axiosOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type EditCustomCodeFromConfigurationMutationResult = NonNullable<Awaited<ReturnType<typeof editCustomCodeFromConfiguration>>>
    export type EditCustomCodeFromConfigurationMutationBody = UpdateCustomCodeInput
    export type EditCustomCodeFromConfigurationMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Edit Custom Code
 */
export const useEditCustomCodeFromConfiguration = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof editCustomCodeFromConfiguration>>, TError,{configurationId: string;data: UpdateCustomCodeInput}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof editCustomCodeFromConfiguration>>,
        TError,
        {configurationId: string;data: UpdateCustomCodeInput},
        TContext
      > => {
      return useMutation(getEditCustomCodeFromConfigurationMutationOptions(options), queryClient);
    }
    /**
 * Accepts a CSV payload in JSON body.

Expected CSV headers:
    code_number,code_system,display_name

Returns:
    UploadCustomCodesResponse
 * @summary Upload Custom Codes Csv
 */
export const uploadCustomCodesCsv = (
    configurationId: string,
    uploadCustomCodesCsvInput: UploadCustomCodesCsvInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UploadCustomCodesPreviewResponse>> => {
    
    
    return axios.default.post(
      `/api/v1/configurations/${configurationId}/custom-codes/upload`,
      uploadCustomCodesCsvInput,options
    );
  }



export const getUploadCustomCodesCsvMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadCustomCodesCsv>>, TError,{configurationId: string;data: UploadCustomCodesCsvInput}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof uploadCustomCodesCsv>>, TError,{configurationId: string;data: UploadCustomCodesCsvInput}, TContext> => {

const mutationKey = ['uploadCustomCodesCsv'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadCustomCodesCsv>>, {configurationId: string;data: UploadCustomCodesCsvInput}> = (props) => {
          const {configurationId,data} = props ?? {};

          return  uploadCustomCodesCsv(configurationId,data,axiosOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UploadCustomCodesCsvMutationResult = NonNullable<Awaited<ReturnType<typeof uploadCustomCodesCsv>>>
    export type UploadCustomCodesCsvMutationBody = UploadCustomCodesCsvInput
    export type UploadCustomCodesCsvMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Upload Custom Codes Csv
 */
export const useUploadCustomCodesCsv = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadCustomCodesCsv>>, TError,{configurationId: string;data: UploadCustomCodesCsvInput}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadCustomCodesCsv>>,
        TError,
        {configurationId: string;data: UploadCustomCodesCsvInput},
        TContext
      > => {
      return useMutation(getUploadCustomCodesCsvMutationOptions(options), queryClient);
    }
    /**
 * Confirm and save custom codes from preview list.
 * @summary Confirm Upload Custom Codes Csv
 */
export const confirmUploadCustomCodesCsv = (
    configurationId: string,
    confirmUploadCustomCodesInput: ConfirmUploadCustomCodesInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UploadCustomCodesResponse>> => {
    
    
    return axios.default.post(
      `/api/v1/configurations/${configurationId}/custom-codes/confirm`,
      confirmUploadCustomCodesInput,options
    );
  }



export const getConfirmUploadCustomCodesCsvMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmUploadCustomCodesCsv>>, TError,{configurationId: string;data: ConfirmUploadCustomCodesInput}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof confirmUploadCustomCodesCsv>>, TError,{configurationId: string;data: ConfirmUploadCustomCodesInput}, TContext> => {

const mutationKey = ['confirmUploadCustomCodesCsv'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof confirmUploadCustomCodesCsv>>, {configurationId: string;data: ConfirmUploadCustomCodesInput}> = (props) => {
          const {configurationId,data} = props ?? {};

          return  confirmUploadCustomCodesCsv(configurationId,data,axiosOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ConfirmUploadCustomCodesCsvMutationResult = NonNullable<Awaited<ReturnType<typeof confirmUploadCustomCodesCsv>>>
    export type ConfirmUploadCustomCodesCsvMutationBody = ConfirmUploadCustomCodesInput
    export type ConfirmUploadCustomCodesCsvMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Confirm Upload Custom Codes Csv
 */
export const useConfirmUploadCustomCodesCsv = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof confirmUploadCustomCodesCsv>>, TError,{configurationId: string;data: ConfirmUploadCustomCodesInput}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof confirmUploadCustomCodesCsv>>,
        TError,
        {configurationId: string;data: ConfirmUploadCustomCodesInput},
        TContext
      > => {
      return useMutation(getConfirmUploadCustomCodesCsvMutationOptions(options), queryClient);
    }
    /**
 * Delete a custom code from a configuration.

Args:
    configuration_id (UUID): The ID of the configuration to modify.
    system (str): System of the custom code.
    code (str): Code of the custom code.
    user (dict[str, Any]): The logged-in user.
    db (AsyncDatabaseConnection): The database connection.

Raises:
    HTTPException: 400 if system is not provided
    HTTPException: 400 if code is not provided
    HTTPException: 404 if configuration can't be found
    HTTPException: 409 if configuration is not a draft and therefore not editable
    HTTPException: 500 if configuration can't be updated

Returns:
    ConfigurationCustomCodeResponse: The updated configuration
 * @summary Delete Custom Code
 */
export const deleteCustomCodeFromConfiguration = (
    configurationId: string,
    system: string,
    code: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ConfigurationCustomCodeResponse>> => {
    
    
    return axios.default.delete(
      `/api/v1/configurations/${configurationId}/custom-codes/${system}/${code}`,options
    );
  }



export const getDeleteCustomCodeFromConfigurationMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCustomCodeFromConfiguration>>, TError,{configurationId: string;system: string;code: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCustomCodeFromConfiguration>>, TError,{configurationId: string;system: string;code: string}, TContext> => {

const mutationKey = ['deleteCustomCodeFromConfiguration'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCustomCodeFromConfiguration>>, {configurationId: string;system: string;code: string}> = (props) => {
          const {configurationId,system,code} = props ?? {};

          return  deleteCustomCodeFromConfiguration(configurationId,system,code,axiosOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCustomCodeFromConfigurationMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCustomCodeFromConfiguration>>>
    
    export type DeleteCustomCodeFromConfigurationMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Delete Custom Code
 */
export const useDeleteCustomCodeFromConfiguration = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCustomCodeFromConfiguration>>, TError,{configurationId: string;system: string;code: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCustomCodeFromConfiguration>>,
        TError,
        {configurationId: string;system: string;code: string},
        TContext
      > => {
      return useMutation(getDeleteCustomCodeFromConfigurationMutationOptions(options), queryClient);
    }
    /**
 * Determines whether a custom code update is valid or not.

If the desired code is already associated with the configuration, then the update is
invalid.

Args:
    configuration_id (UUID): The configuration ID
    body (ValidateCustomCodeInput): Body including the code to validate
    user (DbUser, optional): The logged in user
    db (AsyncDatabaseConnection, optional): The database connection

Returns:
    bool: Returns True if the code name has not been used, otherwise returns False
 * @summary Validate Custom Code
 */
export const validateCustomCodeFromConfiguration = (
    configurationId: string,
    validateCustomCodeInput: ValidateCustomCodeInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ValidateCustomCodeResponse>> => {
    
    
    return axios.default.post(
      `/api/v1/configurations/${configurationId}/custom-codes/validate`,
      validateCustomCodeInput,options
    );
  }



export const getValidateCustomCodeFromConfigurationMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof validateCustomCodeFromConfiguration>>, TError,{configurationId: string;data: ValidateCustomCodeInput}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof validateCustomCodeFromConfiguration>>, TError,{configurationId: string;data: ValidateCustomCodeInput}, TContext> => {

const mutationKey = ['validateCustomCodeFromConfiguration'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof validateCustomCodeFromConfiguration>>, {configurationId: string;data: ValidateCustomCodeInput}> = (props) => {
          const {configurationId,data} = props ?? {};

          return  validateCustomCodeFromConfiguration(configurationId,data,axiosOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ValidateCustomCodeFromConfigurationMutationResult = NonNullable<Awaited<ReturnType<typeof validateCustomCodeFromConfiguration>>>
    export type ValidateCustomCodeFromConfigurationMutationBody = ValidateCustomCodeInput
    export type ValidateCustomCodeFromConfigurationMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Validate Custom Code
 */
export const useValidateCustomCodeFromConfiguration = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof validateCustomCodeFromConfiguration>>, TError,{configurationId: string;data: ValidateCustomCodeInput}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof validateCustomCodeFromConfiguration>>,
        TError,
        {configurationId: string;data: ValidateCustomCodeInput},
        TContext
      > => {
      return useMutation(getValidateCustomCodeFromConfigurationMutationOptions(options), queryClient);
    }
    /**
 * Create a CSV export of a configuration and all associated codes.
 * @summary Get Configuration Export
 */
export const getConfigurationExport = (
    configurationId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.get(
      `/api/v1/configurations/${configurationId}/export`,options
    );
  }




export const getGetConfigurationExportQueryKey = (configurationId: string,) => {
    return [
    `/api/v1/configurations/${configurationId}/export`
    ] as const;
    }

    
export const getGetConfigurationExportQueryOptions = <TData = Awaited<ReturnType<typeof getConfigurationExport>>, TError = AxiosError<HTTPValidationError>>(configurationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfigurationExport>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetConfigurationExportQueryKey(configurationId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getConfigurationExport>>> = ({ signal }) => getConfigurationExport(configurationId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(configurationId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getConfigurationExport>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetConfigurationExportQueryResult = NonNullable<Awaited<ReturnType<typeof getConfigurationExport>>>
export type GetConfigurationExportQueryError = AxiosError<HTTPValidationError>


export function useGetConfigurationExport<TData = Awaited<ReturnType<typeof getConfigurationExport>>, TError = AxiosError<HTTPValidationError>>(
 configurationId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfigurationExport>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConfigurationExport>>,
          TError,
          Awaited<ReturnType<typeof getConfigurationExport>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConfigurationExport<TData = Awaited<ReturnType<typeof getConfigurationExport>>, TError = AxiosError<HTTPValidationError>>(
 configurationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfigurationExport>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getConfigurationExport>>,
          TError,
          Awaited<ReturnType<typeof getConfigurationExport>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetConfigurationExport<TData = Awaited<ReturnType<typeof getConfigurationExport>>, TError = AxiosError<HTTPValidationError>>(
 configurationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfigurationExport>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Configuration Export
 */

export function useGetConfigurationExport<TData = Awaited<ReturnType<typeof getConfigurationExport>>, TError = AxiosError<HTTPValidationError>>(
 configurationId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getConfigurationExport>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetConfigurationExportQueryOptions(configurationId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Runs an inline test of a given configuration against an eICR/RR pair.

This endpoint orchestrates the validation and refinement process by:
1. Handling file input, either from a user upload or a default sample file.
2. Calling the `inline_testing` service, which validates that the specified
   configuration's condition is reportable in the provided file.
3. Handling the service response:
    - If validation fails, raises a 400 Bad Request with a specific error.
    - If successful, proceeds with the returned refined document.
4. Packaging the original eICR, RR, and the single refined eICR into a
   new in-memory zip archive.
5. Uploading the archive to S3 and generating a pre-signed download URL.
6. Returning a `ConfigurationTestResponse` with the download URL and details
   of the successful refinement.

Args:
    id: The ID of the configuration to test.
    uploaded_file: An optional user-provided zip file with an eICR and RR.
    create_output_zip: Dependency to create a zip archive in memory.
    upload_zip: Dependency to upload the archive to S3.
    user: The authenticated user making the request.
    db: The database connection.
    sample_zip_path: Path to the default sample zip file.
    logger: The application logger.

Returns:
    A response object containing the original eICR, a URL to download the
    zipped results, and details about the refined condition.
 * @summary Run Configuration Test
 */
export const runInlineConfigurationTest = (
    bodyRunInlineConfigurationTest: BodyRunInlineConfigurationTest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ConfigurationTestResponse>> => {
    
    const formData = new FormData();
formData.append(`id`, bodyRunInlineConfigurationTest.id);
if(bodyRunInlineConfigurationTest.uploaded_file !== undefined && bodyRunInlineConfigurationTest.uploaded_file !== null) {
 formData.append(`uploaded_file`, bodyRunInlineConfigurationTest.uploaded_file);
 }

    return axios.default.post(
      `/api/v1/configurations/test`,
      formData,options
    );
  }



export const getRunInlineConfigurationTestMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof runInlineConfigurationTest>>, TError,{data: BodyRunInlineConfigurationTest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof runInlineConfigurationTest>>, TError,{data: BodyRunInlineConfigurationTest}, TContext> => {

const mutationKey = ['runInlineConfigurationTest'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof runInlineConfigurationTest>>, {data: BodyRunInlineConfigurationTest}> = (props) => {
          const {data} = props ?? {};

          return  runInlineConfigurationTest(data,axiosOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RunInlineConfigurationTestMutationResult = NonNullable<Awaited<ReturnType<typeof runInlineConfigurationTest>>>
    export type RunInlineConfigurationTestMutationBody = BodyRunInlineConfigurationTest
    export type RunInlineConfigurationTestMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Run Configuration Test
 */
export const useRunInlineConfigurationTest = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof runInlineConfigurationTest>>, TError,{data: BodyRunInlineConfigurationTest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof runInlineConfigurationTest>>,
        TError,
        {data: BodyRunInlineConfigurationTest},
        TContext
      > => {
      return useMutation(getRunInlineConfigurationTestMutationOptions(options), queryClient);
    }
    /**
 * Create a new custom section for a given configuration ID.

Args:
    configuration_id (UUID): The ID of the configuration
    section_input (CustomSectionInput): Desired properties of the section
    user (DbUser): The logged-in user
    db (AsyncDatabaseConnection): The database connection
 * @summary Insert Custom Section
 */
export const addCustomSection = (
    configurationId: string,
    addSectionInput: AddSectionInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    
    
    return axios.default.post(
      `/api/v1/configurations/${configurationId}/sections`,
      addSectionInput,{
    ...options,}
    );
  }



export const getAddCustomSectionMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addCustomSection>>, TError,{configurationId: string;data: AddSectionInput}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof addCustomSection>>, TError,{configurationId: string;data: AddSectionInput}, TContext> => {

const mutationKey = ['addCustomSection'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addCustomSection>>, {configurationId: string;data: AddSectionInput}> = (props) => {
          const {configurationId,data} = props ?? {};

          return  addCustomSection(configurationId,data,axiosOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type AddCustomSectionMutationResult = NonNullable<Awaited<ReturnType<typeof addCustomSection>>>
    export type AddCustomSectionMutationBody = AddSectionInput
    export type AddCustomSectionMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Insert Custom Section
 */
export const useAddCustomSection = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addCustomSection>>, TError,{configurationId: string;data: AddSectionInput}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addCustomSection>>,
        TError,
        {configurationId: string;data: AddSectionInput},
        TContext
      > => {
      return useMutation(getAddCustomSectionMutationOptions(options), queryClient);
    }
    /**
 * Delete a custom section.

Args:
    configuration_id (UUID): ID of the configuration with custom section to delete
    section_input (DeleteCustomSectionInput): Custom section deletion input
    user (DbUser): The logged in user
    db (AsyncDatabaseConnection): The database connection

Raises:
    HTTPException: 404 if configuration isn't found
    HTTPException: 409 if configuration isn't a draft
    HTTPException: 404 if custom section code to delete isn't found

Returns:
    str: Deleted custom section code
 * @summary Delete Custom Section
 */
export const deleteCustomSection = (
    configurationId: string,
    deleteSectionInput: DeleteSectionInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    
    
    return axios.default.delete(
      `/api/v1/configurations/${configurationId}/sections`,{data:
      deleteSectionInput, 
    ...options,}
    );
  }



export const getDeleteCustomSectionMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCustomSection>>, TError,{configurationId: string;data: DeleteSectionInput}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deleteCustomSection>>, TError,{configurationId: string;data: DeleteSectionInput}, TContext> => {

const mutationKey = ['deleteCustomSection'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCustomSection>>, {configurationId: string;data: DeleteSectionInput}> = (props) => {
          const {configurationId,data} = props ?? {};

          return  deleteCustomSection(configurationId,data,axiosOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteCustomSectionMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCustomSection>>>
    export type DeleteCustomSectionMutationBody = DeleteSectionInput
    export type DeleteCustomSectionMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Delete Custom Section
 */
export const useDeleteCustomSection = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCustomSection>>, TError,{configurationId: string;data: DeleteSectionInput}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCustomSection>>,
        TError,
        {configurationId: string;data: DeleteSectionInput},
        TContext
      > => {
      return useMutation(getDeleteCustomSectionMutationOptions(options), queryClient);
    }
    /**
 * Update a section entry for a configuration.

Args:
    configuration_id (UUID): ID of the configuration to update
    section_input (SectionUpdateInput): Updated section info
    user (DbUser): The logged-in user
    db (AsyncDatabaseConnection): Database connection

Raises:
    HTTPException: 400 if the code is not valid, code is in use, or name is in use
    HTTPException: 404 if configuration isn't found
    HTTPException: 409 if configuration is not a draft and therefore not editable
    HTTPException: 500 if section processing can't be updated

Returns:
    UpdateSectionProcessingResponse: The message to show the user
 * @summary Update Section
 */
export const updateSection = (
    configurationId: string,
    sectionUpdateInput: SectionUpdateInput, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    
    
    return axios.default.patch(
      `/api/v1/configurations/${configurationId}/sections`,
      sectionUpdateInput,{
    ...options,}
    );
  }



export const getUpdateSectionMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSection>>, TError,{configurationId: string;data: SectionUpdateInput}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof updateSection>>, TError,{configurationId: string;data: SectionUpdateInput}, TContext> => {

const mutationKey = ['updateSection'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSection>>, {configurationId: string;data: SectionUpdateInput}> = (props) => {
          const {configurationId,data} = props ?? {};

          return  updateSection(configurationId,data,axiosOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateSectionMutationResult = NonNullable<Awaited<ReturnType<typeof updateSection>>>
    export type UpdateSectionMutationBody = SectionUpdateInput
    export type UpdateSectionMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Update Section
 */
export const useUpdateSection = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSection>>, TError,{configurationId: string;data: SectionUpdateInput}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateSection>>,
        TError,
        {configurationId: string;data: SectionUpdateInput},
        TContext
      > => {
      return useMutation(getUpdateSectionMutationOptions(options), queryClient);
    }
    /**
 * Activate the specified configuration.

Args:
    configuration_id (UUID): ID of the configuration to update
    user (DbUser): The logged-in user
    logger (Logger): The standard logger
    db (AsyncDatabaseConnection): Database connection

Raises:
    HTTPException: 400 if configuration can't be activated because of its current state
    HTTPException: 404 if configuration can't be found
    HTTPException: 500 if configuration can't be activated by the server

Returns:
    ActivateConfigurationResponse: Metadata about the activated condition for confirmation
 * @summary Activate Configuration
 */
export const activateConfiguration = (
    configurationId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ConfigurationStatusUpdateResponse>> => {
    
    
    return axios.default.patch(
      `/api/v1/configurations/${configurationId}/activate`,undefined,options
    );
  }



export const getActivateConfigurationMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateConfiguration>>, TError,{configurationId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof activateConfiguration>>, TError,{configurationId: string}, TContext> => {

const mutationKey = ['activateConfiguration'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof activateConfiguration>>, {configurationId: string}> = (props) => {
          const {configurationId} = props ?? {};

          return  activateConfiguration(configurationId,axiosOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ActivateConfigurationMutationResult = NonNullable<Awaited<ReturnType<typeof activateConfiguration>>>
    
    export type ActivateConfigurationMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Activate Configuration
 */
export const useActivateConfiguration = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof activateConfiguration>>, TError,{configurationId: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof activateConfiguration>>,
        TError,
        {configurationId: string},
        TContext
      > => {
      return useMutation(getActivateConfigurationMutationOptions(options), queryClient);
    }
    /**
 * Deactivate the specified configuration.

Args:
    configuration_id (UUID): ID of the configuration to update
    user (DbUser): The logged-in user
    logger (Logger): The standard application logger
    db (AsyncDatabaseConnection): Database connection

Raises:
    HTTPException: 400 if configuration can't be deactivated because of its current state
    HTTPException: 404 if configuration can't be found
    HTTPException: 500 if configuration can't be deactivated by the server

Returns:
    ConfigurationStatusUpdateResponse: Metadata about the activated condition for confirmation
 * @summary Deactivate Configuration
 */
export const deactivateConfiguration = (
    configurationId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ConfigurationStatusUpdateResponse>> => {
    
    
    return axios.default.patch(
      `/api/v1/configurations/${configurationId}/deactivate`,undefined,options
    );
  }



export const getDeactivateConfigurationMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deactivateConfiguration>>, TError,{configurationId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof deactivateConfiguration>>, TError,{configurationId: string}, TContext> => {

const mutationKey = ['deactivateConfiguration'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deactivateConfiguration>>, {configurationId: string}> = (props) => {
          const {configurationId} = props ?? {};

          return  deactivateConfiguration(configurationId,axiosOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeactivateConfigurationMutationResult = NonNullable<Awaited<ReturnType<typeof deactivateConfiguration>>>
    
    export type DeactivateConfigurationMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Deactivate Configuration
 */
export const useDeactivateConfiguration = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deactivateConfiguration>>, TError,{configurationId: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deactivateConfiguration>>,
        TError,
        {configurationId: string},
        TContext
      > => {
      return useMutation(getDeactivateConfigurationMutationOptions(options), queryClient);
    }
    /**
 * Release config lock if held by user.

Args:
    configuration_id (UUID): ID of the configuration to update
    user (DbUser): The logged-in user
    db (AsyncDatabaseConnection): Database connection
 * @summary Release Configuration Lock
 */
export const releaseConfigurationLock = (
    configurationId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.post(
      `/api/v1/configurations/${configurationId}/release-lock`,undefined,options
    );
  }



export const getReleaseConfigurationLockMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof releaseConfigurationLock>>, TError,{configurationId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof releaseConfigurationLock>>, TError,{configurationId: string}, TContext> => {

const mutationKey = ['releaseConfigurationLock'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof releaseConfigurationLock>>, {configurationId: string}> = (props) => {
          const {configurationId} = props ?? {};

          return  releaseConfigurationLock(configurationId,axiosOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type ReleaseConfigurationLockMutationResult = NonNullable<Awaited<ReturnType<typeof releaseConfigurationLock>>>
    
    export type ReleaseConfigurationLockMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Release Configuration Lock
 */
export const useReleaseConfigurationLock = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof releaseConfigurationLock>>, TError,{configurationId: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof releaseConfigurationLock>>,
        TError,
        {configurationId: string},
        TContext
      > => {
      return useMutation(getReleaseConfigurationLockMutationOptions(options), queryClient);
    }
    