version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5

  - package-ecosystem: "pip"
    directories:
      - "/refiner"
      - "/refiner/app/lambda"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
