changelog:
  categories:
    - title: What's Changed 🤔🤔🤔
      labels:
        - "*"
      exclude:
        labels:
          - dependencies
          - tech debt
          - chore
        authors:
          - dependabot
