services:
  message-refiner-service:
    platform: linux/amd64
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    build:
      context: ./refiner
    working_dir: /app
    volumes:
      - ./refiner:/app
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
