services:
  client:
    image: node:22-alpine3.22
    working_dir: /app
    volumes:
      - ./client:/app
      - ./refiner/openapi.json:/app/shared/openapi.json
    command: sh -c "npm i && npm run dev"
    ports:
      - "8081:8081"
    depends_on:
      - refiner-service
  refiner-service:
    image: python:3.14-slim
    platform: linux/amd64
    command: sh -c "pip install -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload"
    working_dir: /app
    volumes:
      - ./refiner:/app
    ports:
      - "8080:8080"
    extra_hosts:
      - "localhost:host-gateway"
    environment:
      - PIP_ROOT_USER_ACTION=ignore
      - ENV=local
      - DB_URL=postgresql://postgres:refiner@db:5432/refiner
      - SESSION_SECRET_KEY=super-secret-key
      - AUTH_PROVIDER=keycloak
      - AUTH_CLIENT_ID=refinerclient
      - AUTH_CLIENT_SECRET=5yXLmlYFPYeQh4HOsO1MvqaLHlVj5aKv
      - AUTH_ISSUER=http://localhost:8082/realms/refiner
      - AUTH_ISSUER_INTERNAL=http://auth:8082/realms/refiner
      - AWS_ACCESS_KEY_ID=refiner
      - AWS_SECRET_ACCESS_KEY=refiner
      - AWS_REGION=us-east-1
      - S3_ENDPOINT_URL=http://localstack:4566
      - S3_UPLOADED_FILES_BUCKET_NAME=refiner-app
    logging:
      driver: "json-file"
    depends_on:
      - db
      - auth
      - localstack
  auth:
    image: quay.io/keycloak/keycloak:26.4.1
    command:
      - "start-dev"
      - "--import-realm"
      - "--http-port=8082"
      - "--hostname-strict=false"
      - "--http-enabled=true"
    ports:
      - "8082:8082"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak/exports:/opt/keycloak/data/import
  db:
    image: postgres:alpine
    restart: on-failure
    user: postgres
    environment:
      - POSTGRES_DB=refiner
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=refiner
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./.justscripts/sql/drop-all.sql:/drop-all.sql
      - pgdata:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - AWS_ACCESS_KEY_ID=refiner
      - AWS_SECRET_ACCESS_KEY=refiner
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack/s3-init.sh:/etc/localstack/init/ready.d/s3-init.sh

  migrate:
    image: migrate/migrate:v4.19.0
    working_dir: /app
    entrypoint: ["tail", "-f", "/dev/null"]
    depends_on:
      - db
    volumes:
      - .:/app
  # Run with `docker compose run --rm seed`
  seed:
    image: python:3.14-slim
    working_dir: /app
    command: >
      sh -c "pip install --no-cache-dir psycopg[binary] python-dotenv &&
             python refiner/scripts/seeding/seed_db.py"
    profiles: ["seed"]
    depends_on:
      - db
    environment:
      - DB_URL=postgresql://postgres:refiner@db:5432/refiner
    volumes:
      - .:/app

volumes:
  pgdata:
  localstack-data:
