services:
  client:
    image: node:20-alpine3.20
    working_dir: /app
    volumes:
      - ./client:/app
    command: sh -c "npm i && npm run dev"
    ports:
    - "8081:8081"
    depends_on:
      - message-refiner-service
  message-refiner-service:
    image: python:3.13-slim
    platform: linux/amd64
    command: sh -c "pip install -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload"
    working_dir: /app
    volumes:
      - ./refiner:/app
    ports:
      - "8080:8080"
    environment:
      - PIP_ROOT_USER_ACTION=ignore
      - AUTH_PROVIDER=keycloak
      - AUTH_CLIENT_ID=refinerclient
      - AUTH_CLIENT_SECRET=VFgmdE2lPIRj0fkFjI9OpQeRXY4UUDA3
      - AUTH_ISSUER=http://auth:8082/realms/refiner
    logging:
      driver: "json-file"
  auth:
    image: quay.io/keycloak/keycloak:26.3.1
    command:
      - "start-dev"
      - "--import-realm"
    ports:
      - "8082:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak/exports:/opt/keycloak/data/import
