services:
  refiner-service:
    environment: &refiner-environment
      - DB_URL=postgresql://postgres@db:5432/refiner
      - DB_PASSWORD=refiner
      - SESSION_SECRET_KEY=super-secret-key
      - AUTH_PROVIDER=keycloak
      - AUTH_CLIENT_ID=refinerclient
      - AUTH_CLIENT_SECRET=5yXLmlYFPYeQh4HOsO1MvqaLHlVj5aKv
      - AUTH_ISSUER=http://localhost:8082/realms/refiner
      - AUTH_ISSUER_INTERNAL=http://auth:8082/realms/refiner
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=refiner
      - AWS_SECRET_ACCESS_KEY=refiner
      - S3_ENDPOINT_URL=http://localstack:4566
      - S3_BUCKET_CONFIG=local-config-bucket

  lambda:
    build:
      context: .
      dockerfile: Dockerfile.lambda
    ports:
      - "9000:8080"
    environment:
      - AWS_ACCESS_KEY_ID=refiner
      - AWS_SECRET_ACCESS_KEY=refiner
      - S3_ENDPOINT_URL=http://localstack:4566
      - S3_BUCKET_CONFIG=local-config-bucket
      - EICR_INPUT_PREFIX=eCRMessageV2/
      - REFINER_INPUT_PREFIX=RefinerInput/
      - REFINER_OUTPUT_PREFIX=RefinerOutput/
      - REFINER_COMPLETE_PREFIX=RefinerComplete/
    depends_on:
      - localstack

  db:
    image: postgres:alpine
    restart: on-failure
    user: postgres
    environment:
      - POSTGRES_DB=refiner
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=refiner
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  auth:
    image: quay.io/keycloak/keycloak:26.6.0
    command:
      - "start-dev"
      - "--import-realm"
      - "--http-port=8082"
      - "--hostname-strict=false"
      - "--http-enabled=true"
    ports:
      - "8082:8082"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - ./keycloak/exports:/opt/keycloak/data/import

  localstack:
    image: localstack/localstack:4
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=refiner
      - AWS_SECRET_ACCESS_KEY=refiner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack/s3-init.sh:/etc/localstack/init/ready.d/s3-init.sh

# Run with `docker compose run --rm seed`
  seed:
    image: python:3.14-slim
    working_dir: /app
    command: >
      sh -c "pip install --no-cache-dir psycopg[binary] python-dotenv &&
             python refiner/scripts/seeding/seed_db.py"
    profiles: ["seed"]
    depends_on:
      - db
    environment:
      - DB_URL=postgresql://postgres@db:5432/refiner
      - DB_PASSWORD=refiner
    volumes:
      - .:/app
