services:
  client:
    image: node:20-alpine3.20
    working_dir: /app
    volumes:
      - ./client:/app
    command: sh -c "npm i && npm run dev"
    ports:
    - "8081:8081"
    depends_on:
      - refiner-service
  refiner-service:
    image: python:3.13-slim
    platform: linux/amd64
    command: sh -c "pip install -r requirements.txt && uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload"
    working_dir: /app
    volumes:
      - ./refiner:/app
    ports:
      - "8080:8080"
    environment:
      - PIP_ROOT_USER_ACTION=ignore
    logging:
      driver: "json-file"
  db:
    image: postgres:alpine
    restart: always
    user: postgres
    environment:
      - POSTGRES_PASSWORD=development
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
