services:
  client:
    image: node:20-alpine3.20
    working_dir: /app
    volumes:
      - ./client:/app
    command: sh -c "npm i && npm run dev"
    ports:
    - "8081:8081"
  message-refiner-service:
    platform: linux/amd64
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload
    build:
      context: ./refiner
    working_dir: /app
    volumes:
      - ./refiner:/app
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
