[tool.ruff]
exclude = [".git", ".pytest_cache", "__pycache__", "docs", "examples/"]
line-length = 88
indent-width = 4
show-fixes = true
target-version = "py313"

[tool.ruff.lint]
select = [
  # flake8 type annotations
  "ANN001",
  "ANN002",
  "ANN201",
  # Pyflakes
  "F",
  # Pydocstyle errors
  "E4",
  "E7",
  "E9",
  # Pydocstyle warnings
  "W",
  # Missing docstring in public module
  "D100",
  # Missing docstring in public class
  "D101",
  # Pydocstyle undocumented-public-method
  "D102",
  # Pydocstyle undocumented-public-function
  "D103",
  # Pydocstyle undocumented-public-package
  "D104",
  # Pydocstyle undocumented-magic-method
  "D105",
  # Pydocstyle undocumented-public-nested-class
  "D106",
  # One-line docstring should fit on one line
  "D200",
  # 1 blank line required between summary line and description
  "D205",
  # Docstring is over-indented
  "D208",
  # Multi-line docstring closing quotes should be on a separate line
  "D209",
  # No whitespaces allowed surrounding docstring text
  "D210",
  # Use """triple double quotes"""
  "D300",
  # Use r""" if any backslashes in a docstring
  "D301",
  # isort
  "I",
  # pyupgrade
  "UP",
]

[tool.ruff.lint.isort]
known-third-party = ["fastapi", "pydantic", "starlette"]

[tool.ruff.lint.per-file-ignores]
"**/tests/*" = ["D", "S", "ANN"]
"**/scripts/*" = ["ANN"]
"**/__init__.py" = ["D"]
