[tool.ruff]
exclude = [".git", ".pytest_cache", "__pycache__", "docs", "examples/"]
line-length = 88
indent-width = 4
show-fixes = true
target-version = "py313"

[tool.ruff.lint]
select = [
  "F",    # Pyflakes
  "E4",   # Pydocstyle errors
  "E7",
  "E9",
  "W",    # Pydocstyle warnings
  "D102", # Pydocstyle undocumented-public-method
  "D103", # Pydocstyle undocumented-public-function
  "D104", # Pydocstyle undocumented-public-package
  "D105", # Pydocstyle undocumented-magic-method
  "D106", # Pydocstyle undocumented-public-nested-class
  "I",    # isort
  "UP",   # pyupgrade
]

[tool.ruff.lint.per-file-ignores]
"**/tests/*" = ["D", "S"]
"**/__init__.py" = ["D"]