/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { AddCustomCodeInputSystem } from './addCustomCodeInputSystem';

/**
 * Input model for adding a custom code to a configuration.
 */
export interface AddCustomCodeInput {
  code: string;
  system: AddCustomCodeInputSystem;
  name: string;
}
