/**
 * Generated by orval v8.2.0 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

export type AddCustomCodeInputSystem = typeof AddCustomCodeInputSystem[keyof typeof AddCustomCodeInputSystem];


export const AddCustomCodeInputSystem = {
  loinc: 'loinc',
  snomed: 'snomed',
  'icd-10': 'icd-10',
  rxnorm: 'rxnorm',
  other: 'other',
} as const;
