/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

/**
 * An event returned by the DB function.
 */
export interface AuditEvent {
  id: string;
  username: string;
  configuration_name: string;
  configuration_version: number;
  condition_id: string;
  action_text: string;
  created_at: string;
}
