/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

export interface AuditEvent {
  id: string;
  username: string;
  configuration_name: string;
  configuration_version: number;
  condition_id: string;
  action_text: string;
  created_at: string;
}
