/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { BodyUploadEcrUploadedFile } from './bodyUploadEcrUploadedFile';

export interface BodyUploadEcr {
  uploaded_file?: BodyUploadEcrUploadedFile;
}
