/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

/**
 * An Enum for code systems.
 */
export type CodeSystem = typeof CodeSystem[keyof typeof CodeSystem];


export const CodeSystem = {
  LOINC: 'LOINC',
  SNOMED: 'SNOMED',
  'ICD-10': 'ICD-10',
  RxNorm: 'RxNorm',
  CVX: 'CVX',
  Other: 'Other',
} as const;
