/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

export type CodeSetStatus = typeof CodeSetStatus[keyof typeof CodeSetStatus];


export const CodeSetStatus = {
  not_expanded: 'not expanded',
  partially_complete: 'partially complete',
  fully_complete: 'fully complete',
} as const;
