/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { CodeCategoryCompletenessStatus } from './codeCategoryCompletenessStatus';
import type { CodeSetStatus } from './codeSetStatus';

/**
 * Condition completeness status model.
 */
export interface CompletenessStatus {
  overall_status: CodeSetStatus;
  last_updated_at: string | null;
  code_category_statuses: CodeCategoryCompletenessStatus[];
}
