/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

export interface ConditionEntry {
  canonical_url: string;
  version: string;
}
