/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * eCR
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

/**
 * Model for a Condition's processing information.
 */
export interface ConditionProcessingInfo {
  condition_specific: boolean;
  sections_processed: string;
  method: string;
}
