/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

/**
 * Model for a Condition.
 */
export interface Condition {
  code: string;
  display_name: string;
  refined_eicr: string;
  refined_rr: string;
  stats: string[];
}
