/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { ConfigurationLockInfoUsername } from './configurationLockInfoUsername';
import type { ConfigurationLockInfoExpiresAt } from './configurationLockInfoExpiresAt';

export interface ConfigurationLockInfo {
  locked: boolean;
  username: ConfigurationLockInfoUsername;
  expires_at: ConfigurationLockInfoExpiresAt;
}
