/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { ConfigurationStatusUpdateResponseStatus } from './configurationStatusUpdateResponseStatus';

export interface ConfigurationStatusUpdateResponse {
  configuration_id: string;
  status: ConfigurationStatusUpdateResponseStatus;
}
