/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { DbConfigurationStatus } from './dbConfigurationStatus';

/**
 * Response model for updating the status a configuration.
 */
export interface ConfigurationStatusUpdateResponse {
  configuration_id: string;
  status: DbConfigurationStatus;
}
