/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { Condition } from './condition';

export interface ConfigurationTestResponse {
  original_eicr: string;
  refined_download_url: string;
  condition: Condition;
}
