/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { Condition } from './condition';

/**
 * Model to represent the response provided to the client when in-line testing is run.
 */
export interface ConfigurationTestResponse {
  original_eicr: string;
  refined_download_key: string;
  condition: Condition;
}
