/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { DbTotalConditionCodeCount } from './dbTotalConditionCodeCount';
import type { DbConfigurationCustomCode } from './dbConfigurationCustomCode';

export interface ConfigurationCustomCodeResponse {
  id: string;
  display_name: string;
  code_sets: DbTotalConditionCodeCount[];
  custom_codes: DbConfigurationCustomCode[];
}
