/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

/**
 * Response model for a custom code upload event.
 */
export interface CustomCodeUploadEventResponse {
  id: string;
  system: string;
  code: string;
  name: string;
}
