/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { DbSectionAction } from './dbSectionAction';
import type { DbSectionType } from './dbSectionType';

export interface DbConfigurationSectionProcessing {
  include: boolean;
  narrative: boolean;
  action: DbSectionAction;
  name: string;
  code: string;
  versions: string[];
  section_type: DbSectionType;
}
