/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { DbSectionAction } from './dbSectionAction';
import type { DbSectionType } from './dbSectionType';

/**
 * Section Processing instructions for a Configuration.

`name` is the section's name.
`code` is the LOINC code for the section.
`versions` is a list of versions this section appears in.
`section_type` is an indicator as to how the section was created.
 */
export interface DbConfigurationSectionProcessing {
  include: boolean;
  narrative: boolean;
  action: DbSectionAction;
  name: string;
  code: string;
  versions: string[];
  section_type: DbSectionType;
}
