/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

export type DbConfigurationCustomCodeSystem = typeof DbConfigurationCustomCodeSystem[keyof typeof DbConfigurationCustomCodeSystem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DbConfigurationCustomCodeSystem = {
  LOINC: 'LOINC',
  SNOMED: 'SNOMED',
  'ICD-10': 'ICD-10',
  RxNorm: 'RxNorm',
} as const;
