/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

export type DbConfigurationStatus = typeof DbConfigurationStatus[keyof typeof DbConfigurationStatus];


export const DbConfigurationStatus = {
  draft: 'draft',
  inactive: 'inactive',
  active: 'active',
} as const;
