/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

/**
 * Conditions returned to the user to be used for filtering events.
 */
export interface EventFilterOption {
  id: string;
  name: string;
  canonical_url: string;
}
