/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { AuditEvent } from './auditEvent';
import type { ConfigurationOption } from './configurationOption';

export interface EventResponse {
  audit_events: AuditEvent[];
  configuration_options: ConfigurationOption[];
}
