/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

/**
 * Response for file upload thresholds.
 */
export interface FileInfoResponse {
  max_mb_for_diff_rendering: number;
  max_mb_for_upload: number;
  max_mb_for_uncompressed: number;
}
