/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

/**
 * Utility class to help Orval ship these values to the frontend.
 */
export const FileInfoResponseValue = {
  max_for_diff_rendering_mb: 2,
  max_for_uncompressed_mb: 15,
} as const;
export type FileInfoResponse = typeof FileInfoResponseValue;
