/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

export type GetConfigurationResponseVersionStatus = typeof GetConfigurationResponseVersionStatus[keyof typeof GetConfigurationResponseVersionStatus];


export const GetConfigurationResponseVersionStatus = {
  draft: 'draft',
  inactive: 'inactive',
  active: 'active',
} as const;
