/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

export interface GetConditionCode {
  code: string;
  system: string;
  description: string;
}
