/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { DbConfigurationStatus } from './dbConfigurationStatus';

export interface GetConfigurationsResponse {
  id: string;
  name: string;
  status: DbConfigurationStatus;
}
