/**
 * Generated by orval v7.15.0 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { GetConfigurationsResponseStatus } from './getConfigurationsResponseStatus';

export interface GetConfigurationsResponse {
  id: string;
  name: string;
  version: number;
  status: GetConfigurationsResponseStatus;
}
