/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { DbTotalConditionCodeCount } from './dbTotalConditionCodeCount';
import type { IncludedCondition } from './includedCondition';
import type { DbConfigurationCustomCode } from './dbConfigurationCustomCode';

export interface GetConfigurationResponse {
  id: string;
  display_name: string;
  code_sets: DbTotalConditionCodeCount[];
  included_conditions: IncludedCondition[];
  custom_codes: DbConfigurationCustomCode[];
}
