/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { DbConfigurationCustomCode } from './dbConfigurationCustomCode';
import type { DbConfigurationSectionProcessing } from './dbConfigurationSectionProcessing';
import type { DbTotalConditionCodeCount } from './dbTotalConditionCodeCount';
import type { GetConfigurationResponseStatus } from './getConfigurationResponseStatus';
import type { GetConfigurationResponseVersion } from './getConfigurationResponseVersion';
import type { IncludedCondition } from './includedCondition';
import type { LockedByUser } from './lockedByUser';

export interface GetConfigurationResponse {
  id: string;
  draft_id: string | null;
  is_draft: boolean;
  condition_id: string;
  condition_canonical_url: string;
  display_name: string;
  status: GetConfigurationResponseStatus;
  code_sets: DbTotalConditionCodeCount[];
  included_conditions: IncludedCondition[];
  custom_codes: DbConfigurationCustomCode[];
  section_processing: DbConfigurationSectionProcessing[];
  deduplicated_codes: string[];
  all_versions: GetConfigurationResponseVersion[];
  version: number;
  active_configuration_id: string | null;
  active_version: number | null;
  latest_version: number;
  is_locked: boolean;
  locked_by: LockedByUser | null;
}
