/**
 * Generated by orval v8.0.2 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { GetConfigurationResponseVersionStatus } from './getConfigurationResponseVersionStatus';

export interface GetConfigurationResponseVersion {
  id: string;
  version: number;
  condition_canonical_url: string;
  status: GetConfigurationResponseVersionStatus;
  created_at: string;
  created_by: string;
  last_activated_at: string | null;
  last_activated_by: string | null;
}
