/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

export type GetConfigurationResponseVersionStatus = typeof GetConfigurationResponseVersionStatus[keyof typeof GetConfigurationResponseVersionStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetConfigurationResponseVersionStatus = {
  draft: 'draft',
  inactive: 'inactive',
  active: 'active',
} as const;
