/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { GetConditionCode } from './getConditionCode';

export interface GetConditionResponse {
  id: string;
  display_name: string;
  available_systems: string[];
  codes: GetConditionCode[];
}
