/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

/**
 * Conditions response model with association flag.
 */
export interface GetConditionsWithAssociationResponse {
  id: string;
  display_name: string;
  associated: boolean;
}
