/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * eCR
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

/**
 * Model for a user-defined configuration.
 */
export interface GetConfigurationsResponse {
  id: string;
  name: string;
  is_active: boolean;
}
