/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

export interface GithubReleaseObject {
  id: string;
  created_at: string;
  name: string;
  body: string;
  prerelease: boolean;
  html_url: string;
}
