/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

export interface IncludedCondition {
  id: string;
  display_name: string;
  canonical_url: string;
  version: string;
  associated: boolean;
}
