/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { Condition } from './condition';

export interface IndependentTestUploadResponse {
  message: string;
  conditions_without_matching_configs: string[];
  refined_conditions_found: number;
  refined_conditions: Condition[];
  unrefined_eicr: string;
  refined_download_key: string;
}
