/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { Condition } from './condition';

export interface RefinedTestingDocument {
  message: string;
  conditions_found: number;
  conditions: Condition[];
  unrefined_eicr: string;
  processing_notes: string[];
  refined_download_url: string;
}
