/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { ReleaseNotes } from './releaseNotes';

/**
 * Type for release information sent to the frontend.
 */
export interface Release {
  id: string;
  created_at: string;
  name: string;
  release_notes: ReleaseNotes[];
  prerelease: boolean;
  url: string;
}
