/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

/**
 * Content of a release note from GitHub.
 */
export interface ReleaseNotes {
  id: string;
  header: string;
  content: string;
}
