/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { DbSectionAction } from './dbSectionAction';

/**
 * Request body for modifying a standard section from the TES.
 */
export interface SectionUpdateInput {
  include?: boolean | null;
  narrative?: boolean | null;
  action?: DbSectionAction | null;
  name?: string | null;
  current_code: string;
  new_code?: string | null;
}
