/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { DbSectionAction } from './dbSectionAction';

/**
 * Model for a single section processing update.
 */
export interface UpdateSectionInput {
  code: string;
  include: boolean;
  narrative: boolean;
  action: DbSectionAction;
}
