/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateCustomCodeInputNewCode } from './updateCustomCodeInputNewCode';
import type { UpdateCustomCodeInputNewSystem } from './updateCustomCodeInputNewSystem';
import type { UpdateCustomCodeInputNewName } from './updateCustomCodeInputNewName';

/**
 * Input model when updating a config's custom code.
 */
export interface UpdateCustomCodeInput {
  system: string;
  code: string;
  new_code: UpdateCustomCodeInputNewCode;
  new_system: UpdateCustomCodeInputNewSystem;
  new_name: UpdateCustomCodeInputNewName;
}
