/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

export type UpdateSectionProcessingEntryAction = typeof UpdateSectionProcessingEntryAction[keyof typeof UpdateSectionProcessingEntryAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateSectionProcessingEntryAction = {
  retain: 'retain',
  refine: 'refine',
  remove: 'remove',
} as const;
