/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

/**
 * Request to update a dismissed notification timestamp for the current user.
 */
export interface UpdateDismissedNotificationRequest {
  key: string;
  value: string;
}
