/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateSectionProcessingEntryAction } from './updateSectionProcessingEntryAction';

/**
 * Model for a single section processing update.
 */
export interface UpdateSectionProcessingEntry {
  code: string;
  action: UpdateSectionProcessingEntryAction;
}
