/**
 * Generated by orval v7.13.0 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { UpdateSectionProcessingEntry } from './updateSectionProcessingEntry';

/**
 * Payload for updating section processing entries.
 */
export interface UpdateSectionProcessingPayload {
  sections: UpdateSectionProcessingEntry[];
}
