/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

/**
 * Input model when updating a config's custom code.
 */
export interface UpdateCustomCodeInput {
  system: string;
  code: string;
  name: string;
  new_code: string | null;
  new_system: string | null;
  new_name: string | null;
}
