/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

/**
 * Request to update notification acknowledgement state for the current user.
 */
export interface UpdateUserNotificationsRequest {
  name: string;
  date_acknowledged: string;
}
