/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { UploadCustomCodesPreviewItem } from './uploadCustomCodesPreviewItem';
import type { UploadCustomCodesPreviewResponseErrors } from './uploadCustomCodesPreviewResponseErrors';

/**
 * Validated CSV preview model for delayed confirmation.
 */
export interface UploadCustomCodesPreviewResponse {
  preview?: UploadCustomCodesPreviewItem[] | null;
  codes_processed?: number | null;
  total_custom_codes_in_configuration?: number | null;
  errors?: UploadCustomCodesPreviewResponseErrors;
}
