/**
 * Generated by orval v8.4.0 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

/**
 * Custom Code CSV response model.
 */
export interface UploadCustomCodesResponse {
  message: string;
  codes_processed: number;
  total_custom_codes_in_configuration: number;
}
