/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { UploadCustomCodesPreviewItemSystem } from './uploadCustomCodesPreviewItemSystem';

/**
 * Validated CSV row ready for confirmation.
 */
export interface UploadCustomCodesPreviewItem {
  code: string;
  system: UploadCustomCodesPreviewItemSystem;
  name: string;
  row?: number | null;
}
