/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { UploadCustomCodesResponseErrors } from './uploadCustomCodesResponseErrors';

/**
 * CSV response model. If errors: errors arr with row+error.
 */
export interface UploadCustomCodesResponse {
  message?: string | null;
  codes_processed?: number | null;
  total_custom_codes_in_configuration?: number | null;
  errors?: UploadCustomCodesResponseErrors;
}
