/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { UploadCustomCodesPreviewItem } from './uploadCustomCodesPreviewItem';

/**
 * Validated CSV preview for delayed confirmation; only valid if preview.
 */
export interface UploadCustomCodesPreviewResponse {
  preview: UploadCustomCodesPreviewItem[];
  codes_processed?: number | null;
  total_custom_codes_in_configuration?: number | null;
}
