/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

export type UploadCustomCodesPreviewItemSystem = typeof UploadCustomCodesPreviewItemSystem[keyof typeof UploadCustomCodesPreviewItemSystem];


export const UploadCustomCodesPreviewItemSystem = {
  LOINC: 'LOINC',
  SNOMED: 'SNOMED',
  'ICD-10': 'ICD-10',
  RxNorm: 'RxNorm',
  Other: 'Other',
} as const;
