/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

/**
 * Input model for Custom Code CSV.
 */
export interface UploadCustomCodesCsvInput {
  /** Full CSV contents as UTF-8 text */
  csv_text: string;
  filename?: string | null;
}
