/**
 * Generated by orval v8.0.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */

/**
 * User information to send to the client.
 */
export interface UserResponse {
  id: string;
  username: string;
  jurisdiction_id: string;
}
