/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import type { UserNotification } from './userNotification';

/**
 * User notification state.
 */
export interface UserNotifications {
  most_recent_app_update?: UserNotification | null;
}
