@hostname=localhost
@refiner_port=8080
@refiner={{hostname}}:{{refiner_port}}

# health check
# we want to see a 200 "OK"
GET http://{{refiner}}/api/healthcheck
Content-Type: application/json
Accept: application/json

###

# request with no parameters
# this should return an error about conditions_to_include being required
POST http://{{refiner}}/api/v1/ecr
Content-Type: application/xml
Accept: application/xml

< CDA_eICR.xml

###

# request with sections to include
# we're passing the loinc code for the social history section
# this should also return an error about conditions_to_include being required
POST http://{{refiner}}/api/v1/ecr?sections_to_include=29762-2
Content-Type: application/xml
Accept: application/xml

< CDA_eICR.xml

###

# post request with conditions to include
# we're passing the snomed code for covid and using
# the sample data with one condition
POST http://{{refiner}}/api/v1/ecr?conditions_to_include=840539006
Content-Type: application/xml
Accept: application/xml

< CDA_eICR.xml

###

# post request with conditions and sections to include
# we're passing the loinc code for the results (labs) section
# and the snomed code for covid using the sample data
# with one condition
POST http://{{refiner}}/api/v1/ecr?conditions_to_include=840539006&sections_to_include=30954-2
Content-Type: application/xml
Accept: application/xml

< CDA_eICR.xml

###

# post request with conditions and sections to include
# we're passing the loinc code for the encounters section
# and the snomed code for covid using sample data with
# one condition
POST http://{{refiner}}/api/v1/ecr?conditions_to_include=840539006&sections_to_include=46240-8
Content-Type: application/xml
Accept: application/xml

< CDA_eICR.xml

###

# post request with a zip that contains an eICR and RR
# with one condition; conditions_to_include is no longer needed
# when the zip contains an RR that contains conditions via its
# coded information organizer
POST http://{{refiner}}/api/v1/ecr/zip-upload HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary{{$timestamp}}

------WebKitFormBoundary{{$timestamp}}
Content-Disposition: form-data; name="file"; filename="mon-mothma-covid-lab-positive.zip"
Content-Type: application/zip

< mon-mothma-one-condition.zip

------WebKitFormBoundary{{$timestamp}}--

###

# post request with a zip that contains an eICR and RR
# with one condition + query param that include the social history section
# this is still a possible way to use the API
POST http://{{refiner}}/api/v1/ecr/zip-upload?sections_to_include=29762-2 HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary{{$timestamp}}

------WebKitFormBoundary{{$timestamp}}
Content-Disposition: form-data; name="file"; filename="mon-mothma-covid-lab-positive.zip"
Content-Type: application/zip

< mon-mothma-one-condition.zip

------WebKitFormBoundary{{$timestamp}}--

###

# post request with a zip that contains an eICR and RR
# with two conditions; the response will show the two
# split eICR documents mapped to the "refined_eicr" key
POST http://{{refiner}}/api/v1/ecr/zip-upload HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary{{$timestamp}}

------WebKitFormBoundary{{$timestamp}}
Content-Disposition: form-data; name="file"; filename="mon-mothma-covid-lab-positive.zip"
Content-Type: application/zip

< mon-mothma-two-conditions.zip

------WebKitFormBoundary{{$timestamp}}--
