/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  FileInfoResponse
} from '../schemas';





/**
 * Fetch application file upload information for frontend display.

Returns:
    FileInfoResponse: Application state information.
 * @summary Get File Upload Limits
 */
export const getFileUploadThresholds = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FileInfoResponse>> => {


    return axios.default.get(
      `/api/v1/info/file-thresholds`,options
    );
  }




export const getGetFileUploadThresholdsQueryKey = () => {
    return [
    `/api/v1/info/file-thresholds`
    ] as const;
    }


export const getGetFileUploadThresholdsQueryOptions = <TData = Awaited<ReturnType<typeof getFileUploadThresholds>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFileUploadThresholds>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetFileUploadThresholdsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getFileUploadThresholds>>> = ({ signal }) => getFileUploadThresholds({ signal, ...axiosOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getFileUploadThresholds>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetFileUploadThresholdsQueryResult = NonNullable<Awaited<ReturnType<typeof getFileUploadThresholds>>>
export type GetFileUploadThresholdsQueryError = AxiosError<unknown>


export function useGetFileUploadThresholds<TData = Awaited<ReturnType<typeof getFileUploadThresholds>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFileUploadThresholds>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFileUploadThresholds>>,
          TError,
          Awaited<ReturnType<typeof getFileUploadThresholds>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFileUploadThresholds<TData = Awaited<ReturnType<typeof getFileUploadThresholds>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFileUploadThresholds>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getFileUploadThresholds>>,
          TError,
          Awaited<ReturnType<typeof getFileUploadThresholds>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetFileUploadThresholds<TData = Awaited<ReturnType<typeof getFileUploadThresholds>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFileUploadThresholds>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get File Upload Limits
 */

export function useGetFileUploadThresholds<TData = Awaited<ReturnType<typeof getFileUploadThresholds>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getFileUploadThresholds>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetFileUploadThresholdsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}






