import re
from dataclasses import dataclass
from typing import TypedDict
from uuid import UUID

SEMVER_VERSION_REGEX = r"\d+\.\d+\.\d+"
DATETIME_VERSION_REGEX = r"\d{8}"
VERSION_REGEX = f"(?:{SEMVER_VERSION_REGEX})|(?:{DATETIME_VERSION_REGEX})"


SYSTEM_MAP = {
    "http://loinc.org": "loinc_codes",
    "http://snomed.info/sct": "snomed_codes",
    "http://hl7.org/fhir/sid/icd-10-cm": "icd10_codes",
    "http://www.nlm.nih.gov/research/umls/rxnorm": "rxnorm_codes",
    "http://hl7.org/fhir/sid/cvx": "cvx_codes",
}


SNOMED_OID = "2.16.840.1.113883.6.96"

CODE_SYSTEM_DATA = {
    "snomed": {
        "oid": SNOMED_OID,
        "display_name": "SNOMED",
        "url": "http://snomed.info/sct",
    },
    "loinc": {
        "oid": "2.16.840.1.113883.6.1",
        "display_name": "LOINC",
        "url": "http://loinc.org",
    },
    "icd10": {
        "oid": "2.16.840.1.113883.6.90",
        "display_name": "ICD-10",
        "url": "http://hl7.org/fhir/sid/icd-10-cm",
    },
    "rxnorm": {
        "oid": "2.16.840.1.113883.6.88",
        "display_name": "RxNorm",
        "url": "http://www.nlm.nih.gov/research/umls/rxnorm",
    },
    "cvx": {
        "oid": "2.16.840.1.113883.12.292",
        "display_name": "CVX",
        "url": "http://hl7.org/fhir/sid/cvx",
    },
    "other": {"oid": "Other", "display_name": "Other", "url": ""},
}


COVERAGE_LEVEL_URL = (
    "http://hl7.org/fhir/uv/crmi/StructureDefinition/crmi-curationCoverageLevel"
)


@dataclass(frozen=True)
class FhirCodeInfo:
    """Class for code-related information we're pulling from the TES artifacts."""

    system_url: str
    code: str
    display: str
    source_url: str
    source_name: str


type SystemOid = str
type SystemSortedFhirInfo = dict[SystemOid, list[FhirCodeInfo]]


# a dictionary representing a single code prepared for categorization by a code system
# * display **could** be empty
type CodePayload = dict[str, str | None]

# a list of processed codes for a specific system
type SystemCodeList = list[CodePayload]

# the map of all unique codes for a condition + version
type ConditionCodePayload = dict[str, SystemCodeList]


type VsCanonicalUrl = str
type VsVersion = str
type VsDict = dict


@dataclass
class CoverageLevel:
    """
    Parsed representation of the crmi-curationCoverageLevel extension.
    """

    level: str
    reason: str | None = None
    date: str | None = None


@dataclass
class AcgCompleteness:
    """
    Metadata for ACG Completeness.
    """

    NOT_INCLUDED = "not included"
    PARTIALLY_COMPLETE = "partially complete"
    FULLY_COMPLETE = "fully complete"


@dataclass
class ContextGrouperInfo:
    """
    Metadata for a single Additional Context Grouper ValueSet.
    """

    name: str
    category: str
    canonical_url: str
    code_count: int
    completeness: str | None


class CodeRow(TypedDict):
    """
    A code row to upsert into the DB.

    UUID is generated by Python to help with seeding of the join tables.
    """

    id: UUID
    display: str
    code: str
    system_id: str
    valueset_url: str
