import csv
import re
from datetime import UTC, datetime
from io import StringIO

import pytest
from fastapi import status
from psycopg.rows import dict_row

from app.api.v1.events import _format_timestamp
from app.db.events.db import insert_event_db
from app.db.events.model import EventInput

FROZEN_TIME = datetime(2026, 7, 13, 15, 50, 0, tzinfo=UTC)
DEFAULT_TIMEZONE = "America/New_York"


def get_url(tz=DEFAULT_TIMEZONE, canonical_url=None):
    url = f"/api/v1/events/export?timezone={tz}"

    if canonical_url is not None:
        url += f"&canonical_url={canonical_url}"

    return url


def parse_csv(content: str) -> list[dict]:
    reader = csv.DictReader(StringIO(content))
    return list(reader)


@pytest.mark.integration
@pytest.mark.asyncio
class TestEventsCsvExport:
    async def test_export_returns_200(self, setup, authed_client):
        """
        Endpoint returns a 200.
        """
        response = await authed_client.get(get_url())
        assert response.status_code == status.HTTP_200_OK

    async def test_export_returns_with_correct_headers(self, setup, authed_client):
        """
        CSV should be returned with correct content type and content-disposition.
        """
        response = await authed_client.get(get_url())

        assert response.status_code == status.HTTP_200_OK
        assert response.headers["content-type"].startswith("text/csv")

        cd_header = response.headers.get("content-disposition", "")
        assert re.search(
            r'filename="Activity_Log_Export_\d{6}_\d{2}_\d{2}_\d{2}\.csv"',
            cd_header,
        ), f"Unexpected Content-Disposition: {cd_header!r}"

    async def test_export_has_expected_headers(self, setup, authed_client):
        """
        CSV should have only the expected headers.
        """
        response = await authed_client.get(get_url())
        assert response.status_code == status.HTTP_200_OK
        headers = response.text.splitlines()[0].split(",")
        assert headers == ["Name", "Condition", "Action", "Date"]

    @pytest.mark.parametrize(
        "timezone",
        [
            "America/New_York",
            "America/Los_Angeles",
            "America/Chicago",
            "UTC",
        ],
    )
    async def test_row_data_has_expected_format(
        self,
        timezone,
        setup,
        authed_client,
        create_config,
        get_event_by_id,
        get_condition_id,
        test_username,
        test_user_id,
        test_user_jurisdiction_id,
        db_pool,
    ):
        """
        CSV row should be formatted appropriately. "Date" should be formatted as the user's local timezone.
        """

        condition_id = await get_condition_id("COVID-19")
        configuration = await create_config(condition_id)
        configuration_id = configuration["id"]

        async with db_pool.get_connection() as conn:
            async with conn.cursor(row_factory=dict_row) as cur:
                event_id = await insert_event_db(
                    event=EventInput(
                        configuration_id=configuration_id,
                        jurisdiction_id=test_user_jurisdiction_id,
                        action_text="Test event",
                        event_type="add_code",
                        user_id=test_user_id,
                    ),
                    cursor=cur,
                )
                assert event_id is not None
        response = await authed_client.get(get_url(timezone))
        assert response.status_code == status.HTTP_200_OK

        rows = parse_csv(response.text)
        assert len(rows) == 2

        event = await get_event_by_id(event_id)
        assert event is not None

        expected_datetime = _format_timestamp(dt=event["created_at"], timezone=timezone)

        # check event generated by config insert
        assert rows[1]["Name"] == test_username
        assert rows[1]["Condition"] == "COVID-19 (Version 1)"
        assert rows[1]["Action"] == "Created configuration"

        # check our test event
        assert rows[0]["Name"] == test_username
        assert rows[0]["Condition"] == "COVID-19 (Version 1)"
        assert rows[0]["Action"] == "Test event"

        # check the datetime format since we have this info
        assert rows[0]["Date"] == expected_datetime

    async def test_csv_upload_event_has_codes_in_action(self, setup):
        pass

    async def test_csv_is_filtered_by_canonical_url(
        self,
        setup,
        get_condition_id,
        create_config,
        get_condition_by_id,
        authed_client,
        test_username,
    ):
        covid_id = await get_condition_id("COVID-19")
        await create_config(covid_id)

        flu_id = await get_condition_id("Influenza")
        flu = await get_condition_by_id(flu_id)
        await create_config(flu_id)

        # filter by flu
        response = await authed_client.get(get_url(canonical_url=flu["canonical_url"]))
        assert response.status_code == status.HTTP_200_OK

        rows = parse_csv(response.text)
        assert len(rows) == 1  # flu creation event only

        assert rows[0]["Name"] == test_username
        assert rows[0]["Condition"] == "Influenza (Version 1)"
        assert rows[0]["Action"] == "Created configuration"
        assert rows[0]["Date"]
