import csv
import re
from datetime import UTC, datetime
from io import StringIO

import pytest
from fastapi import status
from psycopg.rows import dict_row

from app.api.v1.configurations.custom_codes.model import AddCustomCodeInput
from app.api.v1.events import _format_timestamp
from app.db.code_systems.db import get_code_systems_db
from app.db.events.db import insert_event_db
from app.db.events.model import EventInput

FROZEN_TIME = datetime(2026, 7, 13, 15, 50, 0, tzinfo=UTC)
DEFAULT_TIMEZONE = "America/New_York"


def get_url(tz=DEFAULT_TIMEZONE, canonical_url=None):
    url = f"/api/v1/events/export?timezone={tz}"

    if canonical_url is not None:
        url += f"&canonical_url={canonical_url}"

    return url


def parse_csv(content: str) -> list[dict]:
    reader = csv.DictReader(StringIO(content))
    return list(reader)


@pytest.mark.integration
@pytest.mark.asyncio
class TestEventsCsvExport:
    async def test_export_returns_200(self, setup, authed_client):
        """
        Endpoint returns a 200.
        """
        response = await authed_client.get(get_url())
        assert response.status_code == status.HTTP_200_OK

    async def test_export_returns_with_correct_headers(self, setup, authed_client):
        """
        CSV should be returned with correct content type and content-disposition.
        """
        response = await authed_client.get(get_url())

        assert response.status_code == status.HTTP_200_OK
        assert response.headers["content-type"].startswith("text/csv")

        cd_header = response.headers.get("content-disposition", "")
        assert re.search(
            r'filename="Activity_Log_Export_\d{6}_\d{2}_\d{2}_\d{2}\.csv"',
            cd_header,
        ), f"Unexpected Content-Disposition: {cd_header!r}"

    async def test_export_has_expected_csv_headers(self, setup, authed_client):
        """
        CSV should have only the expected headers.
        """
        response = await authed_client.get(get_url())
        assert response.status_code == status.HTTP_200_OK
        headers = response.text.splitlines()[0].split(",")
        assert headers == ["Name", "Condition", "Action", "Date"]

    async def test_invalid_timezone_returns_400(self, setup, authed_client):
        """
        Client providing an invalid timezone should return a 400.
        """
        response = await authed_client.get(get_url(tz="Incorrect/Timezone"))
        assert response.status_code == status.HTTP_400_BAD_REQUEST

    @pytest.mark.parametrize(
        "timezone",
        [
            "America/New_York",
            "America/Los_Angeles",
            "America/Chicago",
            "UTC",
        ],
    )
    async def test_row_data_has_expected_format(
        self,
        timezone,
        setup,
        authed_client,
        create_config,
        get_event_by_id,
        get_condition_id,
        test_username,
        test_user_id,
        test_user_jurisdiction_id,
        db_pool,
    ):
        """
        CSV row should be formatted appropriately. "Date" should be formatted as the user's local timezone.
        """

        condition_id = await get_condition_id("COVID-19")
        configuration = await create_config(condition_id)
        configuration_id = configuration["id"]

        async with db_pool.get_connection() as conn:
            async with conn.cursor(row_factory=dict_row) as cur:
                event_id = await insert_event_db(
                    event=EventInput(
                        configuration_id=configuration_id,
                        jurisdiction_id=test_user_jurisdiction_id,
                        action_text="Test event",
                        event_type="add_code",
                        user_id=test_user_id,
                    ),
                    cursor=cur,
                )
                assert event_id is not None
        response = await authed_client.get(get_url(timezone))
        assert response.status_code == status.HTTP_200_OK

        rows = parse_csv(response.text)
        assert len(rows) == 3

        event = await get_event_by_id(event_id)
        assert event is not None

        expected_datetime = _format_timestamp(dt=event["created_at"], timezone=timezone)

        # Find events by action rather than relying on ordering for events
        # that may have the same created_at timestamp.
        created_event = next(
            row for row in rows if row["Action"] == "Created configuration"
        )
        initial_code_set_event = next(
            row for row in rows if row["Action"] == "Added 'COVID-19' code set"
        )
        test_event = next(row for row in rows if row["Action"] == "Test event")

        # check event generated by config insert
        assert created_event["Name"] == test_username
        assert created_event["Condition"] == "COVID-19 (Version 1)"

        # check initial code set event generated by config insert
        assert initial_code_set_event["Name"] == test_username
        assert initial_code_set_event["Condition"] == "COVID-19 (Version 1)"

        # check our test event
        assert test_event["Name"] == test_username
        assert test_event["Condition"] == "COVID-19 (Version 1)"

        # check the datetime format since we have this info
        assert test_event["Date"] == expected_datetime

    async def test_csv_upload_event_has_codes_in_action(
        self,
        setup,
        upload_custom_codes,
        get_condition_id,
        create_config,
        authed_client,
        db_pool,
    ):
        """
        A custom codes upload event should display the code information directly below the
        action text.

        The format will look like this:
        ```
        Added 2 custom codes from CSV
        SNOMED | tc0 | tc0-name
        ICD-10 | tc1 | tc1-name
        ```
        """
        covid_id = await get_condition_id("COVID-19")
        config = await create_config(covid_id)

        systems = await get_code_systems_db(db=db_pool)
        snomed = next((s for s in systems if s.key == "snomed"), None)
        assert snomed, "Could not find system with key 'snomed'"

        icd_10 = next((s for s in systems if s.key == "icd10"), None)
        assert icd_10, "Could not find system with key 'icd10'"

        await upload_custom_codes(
            config["id"],
            [
                AddCustomCodeInput(code="tc0", system_id=snomed.id, display="tc0-name"),
                AddCustomCodeInput(code="tc1", system_id=icd_10.id, display="tc1-name"),
            ],
        )

        expected_action_text = "Added 2 custom codes from CSV\n"
        expected_tc0_formatted = "SNOMED | tc0 | tc0-name"
        expected_tc1_formatted = "ICD-10 | tc1 | tc1-name"

        response = await authed_client.get(get_url())
        assert response.status_code == status.HTTP_200_OK

        rows = parse_csv(response.text)
        assert (
            len(rows) == 3
        )  # create config (which now includes a code addition), upload codes

        custom_code_event = next(
            row for row in rows if expected_action_text in row["Action"]
        )

        assert expected_tc0_formatted in custom_code_event["Action"]
        assert expected_tc1_formatted in custom_code_event["Action"]

    async def test_csv_is_not_filtered_when_canonical_url_missing(
        self,
        setup,
        get_condition_id,
        create_config,
        authed_client,
        test_username,
        activate_config,
    ):
        """
        CSV contains events for all conditions when no canonical URL is provided for filtering.
        """
        # create covid draft
        covid_id = await get_condition_id("COVID-19")
        await create_config(covid_id)

        # create flu draft
        flu_id = await get_condition_id("Influenza")
        flu_config = await create_config(flu_id)

        # activate flu
        await activate_config(flu_config["id"])

        # create flu v2 draft
        await create_config(flu_id)

        # filter by flu
        response = await authed_client.get(get_url())
        assert response.status_code == status.HTTP_200_OK

        rows = parse_csv(response.text)

        # COVID creation (& code added), flu creation (& code added), flu activation, flu creation v2
        assert len(rows) == 6

        influenza_v2_created = next(
            row
            for row in rows
            if row["Condition"] == "Influenza (Version 2)"
            and row["Action"] == "Created configuration"
        )

        influenza_v1_created = next(
            row
            for row in rows
            if row["Condition"] == "Influenza (Version 1)"
            and row["Action"] == "Created configuration"
        )

        influenza_v1_code_set_added = next(
            row
            for row in rows
            if row["Condition"] == "Influenza (Version 1)"
            and row["Action"] == "Added 'Influenza' code set"
        )

        influenza_activated = next(
            row
            for row in rows
            if row["Condition"] == "Influenza (Version 1)"
            and row["Action"] == "Activated configuration"
        )

        covid_v1_created = next(
            row
            for row in rows
            if row["Condition"] == "COVID-19 (Version 1)"
            and row["Action"] == "Created configuration"
        )

        covid_v1_code_set_added = next(
            row
            for row in rows
            if row["Condition"] == "COVID-19 (Version 1)"
            and row["Action"] == "Added 'COVID-19' code set"
        )

        for row in (
            influenza_v2_created,
            influenza_v1_created,
            influenza_v1_code_set_added,
            influenza_activated,
            covid_v1_created,
            covid_v1_code_set_added,
        ):
            assert row["Name"] == test_username
            assert row["Date"]

    async def test_csv_is_filtered_by_canonical_url(
        self,
        setup,
        get_condition_id,
        create_config,
        get_condition_by_id,
        authed_client,
        test_username,
    ):
        """
        CSV should be filtered to a specific condition when provided with the condition's
        canonical URL.
        """
        covid_id = await get_condition_id("COVID-19")
        await create_config(covid_id)

        flu_id = await get_condition_id("Influenza")
        flu = await get_condition_by_id(flu_id)
        await create_config(flu_id)

        # filter by flu
        response = await authed_client.get(get_url(canonical_url=flu["canonical_url"]))
        assert response.status_code == status.HTTP_200_OK

        rows = parse_csv(response.text)
        assert len(rows) == 2  # flu creation (& code added)

        created_event = next(
            row for row in rows if row["Action"] == "Created configuration"
        )

        code_set_event = next(
            row for row in rows if row["Action"] == "Added 'Influenza' code set"
        )

        assert created_event["Name"] == test_username
        assert created_event["Condition"] == "Influenza (Version 1)"
        assert created_event["Date"]

        assert code_set_event["Name"] == test_username
        assert code_set_event["Condition"] == "Influenza (Version 1)"
        assert code_set_event["Date"]

    async def test_code_set_export_has_expected_content(
        self,
        setup,
        authed_client,
        create_config,
        get_condition_id,
    ):
        """
        A code-set event export should contain the historical condition's codes
        using the expected CSV headers.
        """
        condition_name = "COVID-19"
        condition_id = await get_condition_id(condition_name)

        await create_config(condition_id)

        # Get the activity log entry created for the initial code set.
        events_response = await authed_client.get("/api/v1/events/")
        assert events_response.status_code == status.HTTP_200_OK

        audit_events = events_response.json()["audit_events"]

        code_set_event = next(
            event
            for event in audit_events
            if event["action_text"] == f"Added '{condition_name}' code set"
        )

        response = await authed_client.get(
            f"/api/v1/events/{code_set_event['id']}/codes/export"
        )

        assert response.status_code == status.HTTP_200_OK
        assert response.headers["content-type"].startswith("text/csv")

        event_created_at = datetime.fromisoformat(code_set_event["created_at"])
        expected_timestamp = event_created_at.strftime("%m%d%y_%H_%M_%S")

        content_disposition = response.headers["content-disposition"]

        assert content_disposition == (
            f'attachment; filename="'
            f'{condition_name}_code_set_added_{expected_timestamp}.csv"'
        )

        rows = parse_csv(response.text)

        assert len(rows) == code_set_event["code_count"]
        assert len(rows) > 0

        assert list(rows[0].keys()) == [
            "Condition grouper",
            "Code",
            "Code system",
            "Display name",
        ]

        assert all(row["Condition grouper"] == condition_name for row in rows)
        assert all(row["Code"] for row in rows)
        assert all(row["Code system"] for row in rows)

    async def test_removed_code_set_export_uses_removed_filename(
        self,
        setup,
        authed_client,
        create_config,
        get_condition_id,
        get_event_by_id,
        test_user_id,
        test_user_jurisdiction_id,
        db_pool,
    ):
        """
        A delete_code event should export using "code_set_removed" in the filename.
        """
        condition_name = "COVID-19"
        condition_id = await get_condition_id(condition_name)

        configuration = await create_config(condition_id)

        async with db_pool.get_connection() as conn:
            async with conn.cursor(row_factory=dict_row) as cur:
                event_id = await insert_event_db(
                    event=EventInput(
                        configuration_id=configuration["id"],
                        jurisdiction_id=test_user_jurisdiction_id,
                        user_id=test_user_id,
                        event_type="delete_code",
                        action_text=f"Removed '{condition_name}' code set",
                        condition_id=condition_id,
                        code_count=1,
                    ),
                    cursor=cur,
                )

        event = await get_event_by_id(event_id)
        assert event is not None

        response = await authed_client.get(f"/api/v1/events/{event_id}/codes/export")

        assert response.status_code == status.HTTP_200_OK

        event_created_at = event["created_at"]
        expected_timestamp = event_created_at.strftime("%m%d%y_%H_%M_%S")

        assert response.headers["content-disposition"] == (
            f'attachment; filename="'
            f'{condition_name}_code_set_removed_{expected_timestamp}.csv"'
        )
