services:
  postgres-dev:
    image: postgres:16
    restart: unless-stopped
    # these variables are read from the .env file
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      # The '1_', '2_', and '3_' prefixes ensure they run in the correct order.
      - ./schema/01-base-schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./triggers/01-aggregate-base-groupers.sql:/docker-entrypoint-initdb.d/2_triggers.sql
      - ./triggers/02-update-refinement-cache.sql:/docker-entrypoint-initdb.d/3_cache_trigger.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
