/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ReleasesResponse
} from '../schemas';





/**
 * Hook to get release data from GitHub and serve it to the frontend.

Returns:
    ReleasesResponse: Reponse of release information in a list of ReleaseMetadata
 * @summary Get Releases Data
 */
export const getReleases = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ReleasesResponse>> => {
    
    
    return axios.default.get(
      `/api/v1/releases/`,options
    );
  }




export const getGetReleasesQueryKey = () => {
    return [
    `/api/v1/releases/`
    ] as const;
    }

    
export const getGetReleasesQueryOptions = <TData = Awaited<ReturnType<typeof getReleases>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReleases>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReleasesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReleases>>> = ({ signal }) => getReleases({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReleases>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReleasesQueryResult = NonNullable<Awaited<ReturnType<typeof getReleases>>>
export type GetReleasesQueryError = AxiosError<unknown>


export function useGetReleases<TData = Awaited<ReturnType<typeof getReleases>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReleases>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReleases>>,
          TError,
          Awaited<ReturnType<typeof getReleases>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReleases<TData = Awaited<ReturnType<typeof getReleases>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReleases>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReleases>>,
          TError,
          Awaited<ReturnType<typeof getReleases>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReleases<TData = Awaited<ReturnType<typeof getReleases>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReleases>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Releases Data
 */

export function useGetReleases<TData = Awaited<ReturnType<typeof getReleases>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReleases>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReleasesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




