import subprocess
import json
import sys
from pathlib import Path

def extract_ts_docs():
    output_dir = Path("docs/_data")
    output_dir.mkdir(parents=True, exist_ok=True)

    # Temporary file for raw typedoc output
    raw_json_path = output_dir / "typedoc-raw.json"

    try:
        # Run typedoc with --json to get structured metadata
        # We specify the entry point to the client source
        result = subprocess.run(
            ["npm", "run", "typedoc"],
            capture_output=True,
            text=True,
            check=True,
            cwd="client"
        )

        # Note: typedoc often writes to a directory rather than stdout.
        # We need to check the package.json script first to see where it outputs.
    except subprocess.CalledProcessError as e:
        print(f"Error running typedoc: {e.stderr}", file=sys.stderr)
        sys.exit(1)

def prune_typedoc_json(raw_path: Path):
    with open(raw_path, "r") as f:
        raw_data = json.load(f)

    # Mapping of TypeDoc numeric kinds to human-readable strings
    KIND_MAP = {
        2: "Module",
        64: "Function",
        4096: "Signature",
        2097152: "TypeAlias",
        # Add others as discovered
    }

    def get_comment(obj):
        comment = obj.get("comment")
        if not comment:
            return ""
        summary = comment.get("summary", [])
        return " ".join([s.get("text", "") for s in summary])

    pruned = {
        "modules": []
    }

    for child in raw_data.get("children", []):
        if child.get("kind") == 2: # Module
            module_name = child.get("name", "Unknown")

            # Skip modules in the api/ directory (auto-generated by Orval)
            if module_name.startswith("api/"):
                continue

            module_info = {
                "name": module_name,
                "docstring": get_comment(child),
                "members": []
            }

            for member in child.get("children", []):
                kind = member.get("kind")
                member_info = {
                    "name": member.get("name", "Unknown"),
                    "type": KIND_MAP.get(kind, f"Unknown({kind})"),
                    "docstring": get_comment(member),
                    "lineno": member.get("sources", [{}])[0].get("line", 0) if member.get("sources") else 0
                }

                # Handle signatures for functions/methods
                if "signatures" in member:
                    sigs = []
                    for sig in member["signatures"]:
                        sigs.append({
                            "name": sig.get("name", "Unknown"),
                            "docstring": get_comment(sig),
                            "lineno": sig.get("sources", [{}])[0].get("line", 0) if sig.get("sources") else 0
                        })
                    member_info["signatures"] = sigs

                # If it's a class or interface, extract children
                if kind in [1024, 2048]: # Common Class/Interface kinds
                    children = []
                    for submember in member.get("children", []):
                        children.append({
                            "name": submember.get("name", "Unknown"),
                            "docstring": get_comment(submember),
                            "lineno": submember.get("sources", [{}])[0].get("line", 0) if submember.get("sources") else 0
                        })
                    member_info["methods"] = children

                module_info["members"].append(member_info)

            pruned["modules"].append(module_info)

    return pruned

def main():
    print("Extracting TypeScript API documentation...")
    output_dir = Path("docs/_data")
    output_dir.mkdir(parents=True, exist_ok=True)

    # 1. Run TypeDoc
    # Use the specific doc tsconfig to avoid test files and get JSX support
    # Exclude client/src/api directory (auto-generated by Orval)
    try:
        subprocess.run(
            [
                "npx", "typedoc",
                "--tsconfig", "client/tsconfig.doc.json",
                "--json", "docs/_data/typedoc-raw.json",
                "--exclude", "**/api/**",
                "client/src/**/*.ts",
                "client/src/**/*.tsx"
            ],
            check=True,
            capture_output=True
        )
        print("Ran TypeDoc successfully")
    except subprocess.CalledProcessError as e:
        print(f"Error running typedoc: {e.stderr}", file=sys.stderr)
        sys.exit(1)

    # 2. Prune and filter
    raw_json_path = output_dir / "typedoc-raw.json"
    pruned_data = prune_typedoc_json(raw_json_path)
    module_count = len(pruned_data["modules"])

    with open(output_dir / "typescript-api.json", "w") as f:
        json.dump(pruned_data, f, indent=2)

    print(f"Wrote {module_count} TypeScript modules to {output_dir / 'typescript-api.json'} (excluding api/ directory)")

    # Clean up raw file
    # raw_json_path.unlink() # Temporarily disabled for debugging

if __name__ == "__main__":
    main()
