/**
 * Generated by orval v7.18.0 🍺
 * Do not edit manually.
 * DIBBs eCR Refiner
 * Please visit the repo for more info: https://github.com/CDCgov/dibbs-ecr-refiner
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  BodyUploadEcr,
  HTTPValidationError,
  IndependentTestUploadResponse
} from '.././schemas';





/**
 * Handles the demo upload workflow for eICR refinement.

Steps:
1. Obtain the demo eICR ZIP file (either uploaded by user or from local sample in
    refiner/assets/demo/mon-mothma-covid-influenza.zip).
2. Read and validate the XML files (eICR and RR) from the ZIP (XMLFiles object).
3. Call the service layer (`independent_testing`) to orchestrate the refinement workflow.
4. For each unique reportable condition code found in the RR (and having a configuration),
    build a refined XML document and collect metadata. The code used is the actual code
    from the RR that triggered the match, not a canonical or database code.
5. Package all refined and original files into a ZIP.
6. Upload the ZIP to S3 and get a download URL.
7. Construct and return the response model for the frontend, including per-condition
    refinement results and a link to the ZIP of outputs.

Any exceptions during file processing or workflow execution are caught and mapped to HTTP errors.
 * @summary Demo Upload
 */
export const uploadEcr = (
    bodyUploadEcr: BodyUploadEcr, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<IndependentTestUploadResponse>> => {
    
    const formData = new FormData();
if(bodyUploadEcr.uploaded_file !== undefined && bodyUploadEcr.uploaded_file !== null) {
 formData.append(`uploaded_file`, bodyUploadEcr.uploaded_file)
 }

    return axios.default.post(
      `/api/v1/demo/upload`,
      formData,options
    );
  }



export const getUploadEcrMutationOptions = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadEcr>>, TError,{data: BodyUploadEcr}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof uploadEcr>>, TError,{data: BodyUploadEcr}, TContext> => {

const mutationKey = ['uploadEcr'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadEcr>>, {data: BodyUploadEcr}> = (props) => {
          const {data} = props ?? {};

          return  uploadEcr(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadEcrMutationResult = NonNullable<Awaited<ReturnType<typeof uploadEcr>>>
    export type UploadEcrMutationBody = BodyUploadEcr
    export type UploadEcrMutationError = AxiosError<HTTPValidationError>

    /**
 * @summary Demo Upload
 */
export const useUploadEcr = <TError = AxiosError<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadEcr>>, TError,{data: BodyUploadEcr}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadEcr>>,
        TError,
        {data: BodyUploadEcr},
        TContext
      > => {

      const mutationOptions = getUploadEcrMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    