name: Build and push Refiner image to GHCR

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - "**/*.py"
      - ".github/workflows/docker-ghcr.yml"

  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref (branch or tag) to build"
        required: false
        default: main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Sanitize branch name for tagging
        id: vars
        run: |
          BRANCH_NAME="${{ github.event.inputs.ref || github.ref_name }}"
          SAFE_TAG=$(echo "$BRANCH_NAME" | tr '/' '-' | tr '[:upper:]' '[:lower:]')
          echo "safe_branch=$SAFE_TAG" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: |
            ghcr.io/${{ github.repository_owner }}/dibbs-ecr-refiner:latest
            ghcr.io/${{ github.repository_owner }}/dibbs-ecr-refiner:${{ steps.vars.outputs.safe_branch }}
