name: Linting

on:
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  run-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: pip
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install ruff==0.11.2
      - name: Run linter (ruff)
        run: |
          ruff check --output-format=github .
      - name: Run formatter (ruff)
        run: |
          ruff format --check
