name: Playwright E2E Tests
permissions:
  contents: read
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  e2e:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    services:
        docker:
          image: docker:19.03.12
          options: --privileged
          ports:
            - 5432:5432  # Expose database port for testing
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Just
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -fsSL https://just.systems/install.sh | bash -s -- --to /usr/local/bin
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install Dependencies
        run: npm ci
        working-directory: client
      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            playwright-browsers-${{ runner.os }}-
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: client
      - name: Start Application
        run: just dev up --detach
      - name: Seed Database
        run: just dev run --rm seed
      - name: Run Playwright E2E Tests
        run: npm run e2e
        working-directory: client
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: client/playwright-report/
          retention-days: 30
