name: Playwright E2E Tests
permissions:
  contents: read
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  e2e:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    services:
        docker:
          image: docker:19.03.12
          options: --privileged
          ports:
            - 5432:5432  # Expose database port for testing
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Just
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -fsSL https://just.systems/install.sh | bash -s -- --to /usr/local/bin
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install Dependencies
        run: npm ci
        working-directory: client
      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-browsers-${{ hashFiles('client/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-browsers-
            ${{ runner.os }}-playwright-
            ${{ runner.os }}-
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: client
      - name: Start Application
        run: just dev up --detach
      - name: Wait for Server Startup
        run: |
          for i in {1..24}; do
            if curl -sSf http://localhost:8081/api/healthcheck > /dev/null; then
              echo "Server is up!"
              exit 0
            fi
            echo "Waiting for server startup... ($i/24)"
            sleep 5
          done
          echo "Server did not start within 2 minutes."
          exit 42
      - name: Migrate and Seed Database
        run: |
          just migrate local
          just dev run --rm seed
      - name: Run Playwright E2E Tests
        run: npm run e2e
        working-directory: client
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: client/playwright-report/
          retention-days: 30
